### ISSUE TITLE
Bikestore - too low z-index for the figcaption

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Image-Show#29]
Change:

``` css
.gkIsWrapper-gk_bikestore figure.active figcaption {
    z-index: 4;
}
```

to:

``` css
.gkIsWrapper-gk_bikestore figure.active figcaption {
    z-index: 20;
}
```
