### ISSUE TITLE
Shrink text size "Image Show GK4"

### ISSUE THREAD

**Issue by adriannx** [GavickPro/Image-Show#79]
Hello Tomas Dziuda,

How can shrink text size that It is shown here: "NEW FIFA 14" Titles that i have used is up to 30 characters.

![text](https://cloud.githubusercontent.com/assets/5619504/12054886/5839bcf8-aef5-11e5-9876-8a54c9a63f57.JPG)

i'm using this code on override.css:

.gkIsWrapper-gk_game figcaption h2 {
    font-size: 70px;
}

But doest work on mobil

Best Regards!

**Comment by dziudek** [comment]
Hello,

On mobile the CSS rules are overrided by media queries. Please try to use: 

```css
body .gkIsWrapper-gk_game figcaption h2 {
font-size: 70px!important;
}
```
